apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deployment
  labels:
    env: production
    name: new-deplyment
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      env: production
