apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica-set
  labels:
    env: production
    name: new-repicaset
    app: myapp
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 5
  selector:
    matchLabels:
      env: production
